services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
      - VITE_HOST=0.0.0.0
    networks:
      - hydropal-network
    depends_on:
      - backend

  backend:
    build:
      context: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/hydropal-db
      - FRONTEND_URL=http://frontend:3000
    networks:
      - hydropal-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - hydropal-network

networks:
  hydropal-network:
    driver: bridge

volumes:
  mongo_data: